#Module 2: Data Cleaning and Structuring

In [9]:
import pandas as pd

df = pd.read_csv('/content/military_raw_data.csv')
print("DataFrame reloaded successfully. First 5 rows:")
df.head()

DataFrame reloaded successfully. First 5 rows:

,Country,power_index_rank,population,total_personnel,manpower_fit_for_military_service,manpower_reaching_military_age_annually,active_personnel,reserve_personnel,manpower_paramilitary,capital_cities_by_total_population,...,proven_coal_reserves_by_country,land_area_sq_km,coastline_km,border_coverage,waterway_coverage,capital_city,region,continent,year,alliance
0,United States,1,341963408,150463900,124816644,4445524,1328000,799500,0,NaN,...,248941000000,9833517,19924,12002,41009,"Washington, D.C.",Americas,North America,2026,NATO
1,Russia,2,140820810,69002197,46189226,1267387,1320000,2000000,250000,NaN,...,162166000000,17098242,37653,22407,102000,Moscow,Europe,Europe,2026,Other
2,China,3,1415043270,764123366,626864169,19810606,2035000,510000,625000,NaN,...,143197000000,9596960,14500,22457,27700,Beijing,Asia,Asia,2026,Other
3,India,4,1409128296,662290299,522786598,23955181,1455550,1155000,2527000,NaN,...,111052000000,3287263,7000,13888,14500,New Delhi,Asia,Asia,2026,Other
4,South Korea,5,52081799,26040900,21353538,416654,600000,3100000,120000,NaN,...,326000000,99720,2413,237,1600,Seoul,Asia,Asia,2026,Other

## Standardize Column Names

### Subtask:
Convert all column names to a consistent, standardized format (snake_case) for improved readability and usability.

**Reasoning**:
To standardize the column names to snake_case, I will apply a series of string operations: first converting to lowercase, then replacing spaces and special characters with underscores, and finally cleaning up leading/trailing and multiple underscores. After these transformations, I will print the new column names to verify the changes.

In [10]:
import re

# Convert all column names to lowercase
df.columns = df.columns.str.lower()

# Replace spaces and special characters with underscores
df.columns = df.columns.str.replace(r'[^a-z0-9]+', '_', regex=True)

# Remove leading/trailing underscores and replace multiple underscores with a single one
df.columns = df.columns.str.strip('_').str.replace(r'_{2,}', '_', regex=True)

print("Column names standardized to snake_case:")
print(df.columns.tolist())

Column names standardized to snake_case:
['country', 'power_index_rank', 'population', 'total_personnel', 'manpower_fit_for_military_service', 'manpower_reaching_military_age_annually', 'active_personnel', 'reserve_personnel', 'manpower_paramilitary', 'capital_cities_by_total_population', 'total_aircraft', 'fighter_aircraft', 'attack_aircraft', 'transport_aircraft', 'aircraft_total_trainers', 'aircraft_total_special_mission', 'aircraft_total_tanker_fleet', 'helicopters', 'aircraft_helicopters_attack', 'tanks', 'armored_vehicles', 'armor_self_propelled_guns_total', 'artillery_units', 'armor_mlrs_total', 'naval_assets', 'navy_force_by_tonnage', 'aircraft_carriers', 'navy_helo_carriers', 'navy_submarines', 'navy_destroyers', 'navy_frigates', 'navy_corvettes', 'navy_patrol_coastal_craft', 'navy_mine_warfare_craft', 'defense_budget_usd', 'external_debt_by_country', 'gdp_usd', 'reserves_of_foreign_exchange_and_gold', 'major_serviceable_airports_by_country', 'labor_force_by_country', 'major_ports_and_terminals', 'railway_coverage', 'roadway_coverage', 'oil_production_by_country', 'oil_consumption_by_country', 'proven_oil_reserves_by_country', 'natural_gas_production_by_country', 'natural_gas_consumption_by_country', 'proven_natural_gas_reserves_by_country', 'coal_production_by_country', 'coal_consumption_by_country', 'proven_coal_reserves_by_country', 'land_area_sq_km', 'coastline_km', 'border_coverage', 'waterway_coverage', 'capital_city', 'region', 'continent', 'year', 'alliance']

## Clean and Convert Numeric Metrics

Iterate through columns that represent metrics, remove non-numeric characters, and convert these columns to a suitable numeric data type.

**Reasoning**:
To identify and convert numeric metric columns, I will first define the columns to exclude (categorical/identifier). Then, I will iterate through the remaining columns, cleaning them by removing non-numeric characters and converting them to a numeric data type, coercing errors. This ensures that all numerical data is in a clean and consistent format, ready for analysis and imputation.

In [11]:
import numpy as np

# Define columns that should NOT be treated as numeric metrics
# These are categorical or identifier columns
exclude_columns = ['country', 'capital_city', 'region', 'continent', 'alliance', 'year']

# Iterate through all columns and process them
for col in df.columns:
    if col not in exclude_columns:
        # Check if the column is of object type (potential string values that need cleaning)
        if df[col].dtype == 'object':
            # Remove non-numeric characters (like '$', ',', '%')
            df[col] = df[col].astype(str).str.replace(r'[$,%]', '', regex=True)
            # Handle potential 'M' (Millions) or 'B' (Billions) suffixes by multiplying
            def convert_large_numbers(value):
                if isinstance(value, str):
                    value = value.strip()
                    if value.endswith('B'):
                        return float(value[:-1]) * 1_000_000_000
                    elif value.endswith('M'):
                        return float(value[:-1]) * 1_000_000
                return value
            df[col] = df[col].apply(convert_large_numbers)

        # Convert the column to numeric, coercing any errors to NaN
        # This will convert any remaining strings that couldn't be cleaned, or non-numeric types
        # and also ensure all numeric columns are of a type that can hold NaNs (float)
        df[col] = pd.to_numeric(df[col], errors='coerce')

print("DataFrame Info after cleaning and converting numeric metrics:")
df.info()

print("\nFirst 5 rows of DataFrame after cleaning and converting numeric metrics:")
df.head()

DataFrame Info after cleaning and converting numeric metrics:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 61 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  145 non-null    object
 1   power_index_rank                         145 non-null    int64
 2   population                               145 non-null    int64
 3   total_personnel                          145 non-null    int64
 4   manpower_fit_for_military_service        145 non-null    int64
 5   manpower_reaching_military_age_annually  145 non-null    int64
 6   active_personnel                         145 non-null    int64
 7   reserve_personnel                        145 non-null    int64
 8   manpower_paramilitary                    145 non-null    int64
 9   capital_cities_by_total_population       3 non-null      float64
 10  total_aircraft                           145 non-null    int64
 11  fighter_aircraft                         145 non-null    int64
 12  attack_aircraft                          145 non-null    int64
 13  transport_aircraft                       145 non-null    int64
 14  aircraft_total_trainers                  145 non-null    int64
 15  aircraft_total_special_mission           145 non-null    int64
 16  aircraft_total_tanker_fleet              145 non-null    int64
 17  helicopters                              145 non-null    int64
 18  aircraft_helicopters_attack              145 non-null    int64
 19  tanks                                    145 non-null    int64
 20  armored_vehicles                         145 non-null    int64
 21  armor_self_propelled_guns_total          145 non-null    int64
 22  artillery_units                          145 non-null    int64
 23  armor_mlrs_total                         145 non-null    int64
 24  naval_assets                             145 non-null    int64
 25  navy_force_by_tonnage                    47 non-null     float64
 26  aircraft_carriers                        145 non-null    int64
 27  navy_helo_carriers                       145 non-null    int64
 28  navy_submarines                          145 non-null    int64
 29  navy_destroyers                          145 non-null    int64
 30  navy_frigates                            145 non-null    int64
 31  navy_corvettes                           145 non-null    int64
 32  navy_patrol_coastal_craft                145 non-null    int64
 33  navy_mine_warfare_craft                  145 non-null    int64
 34  defense_budget_usd                       145 non-null    int64
 35  external_debt_by_country                 145 non-null    int64
 36  gdp_usd                                  145 non-null    int64
 37  reserves_of_foreign_exchange_and_gold    145 non-null    int64
 38  major_serviceable_airports_by_country    145 non-null    int64
 39  labor_force_by_country                   145 non-null    int64
 40  major_ports_and_terminals                145 non-null    int64
 41  railway_coverage                         145 non-null    int64
 42  roadway_coverage                         145 non-null    int64
 43  oil_production_by_country                145 non-null    int64
 44  oil_consumption_by_country               145 non-null    int64
 45  proven_oil_reserves_by_country           145 non-null    int64
 46  natural_gas_production_by_country        145 non-null    int64
 47  natural_gas_consumption_by_country       145 non-null    int64
 48  proven_natural_gas_reserves_by_country   145 non-null    int64
 49  coal_production_by_country               145 non-null    int64
 50  coal_consumption_by_country              145 non-null    int64
 51  proven_coal_reserves_by_country          145 non-null    int64
 52  land_area_sq_km                          145 non-null    int64
 53  coastline_km                             145 non-null    int64
 54  border_coverage                          145 non-null    int64
 55  waterway_coverage                        145 non-null    int64
 56  capital_city                             145 non-null    object
 57  region                                   145 non-null    object
 58  continent                                145 non-null    object
 59  year                                     145 non-null    int64
 60  alliance                                 145 non-null    object
dtypes: float64(2), int64(54), object(5)
memory usage: 69.2+ KB

First 5 rows of DataFrame after cleaning and converting numeric metrics:

,country,power_index_rank,population,total_personnel,manpower_fit_for_military_service,manpower_reaching_military_age_annually,active_personnel,reserve_personnel,manpower_paramilitary,capital_cities_by_total_population,...,proven_coal_reserves_by_country,land_area_sq_km,coastline_km,border_coverage,waterway_coverage,capital_city,region,continent,year,alliance
0,United States,1,341963408,150463900,124816644,4445524,1328000,799500,0,NaN,...,248941000000,9833517,19924,12002,41009,"Washington, D.C.",Americas,North America,2026,NATO
1,Russia,2,140820810,69002197,46189226,1267387,1320000,2000000,250000,NaN,...,162166000000,17098242,37653,22407,102000,Moscow,Europe,Europe,2026,Other
2,China,3,1415043270,764123366,626864169,19810606,2035000,510000,625000,NaN,...,143197000000,9596960,14500,22457,27700,Beijing,Asia,Asia,2026,Other
3,India,4,1409128296,662290299,522786598,23955181,1455550,1155000,2527000,NaN,...,111052000000,3287263,7000,13888,14500,New Delhi,Asia,Asia,2026,Other
4,South Korea,5,52081799,26040900,21353538,416654,600000,3100000,120000,NaN,...,326000000,99720,2413,237,1600,Seoul,Asia,Asia,2026,Other

## Handle Missing Values

### Subtask:
Impute missing values in the `capital_cities_by_total_population` and `navy_force_by_tonnage` columns using their respective medians.

**Reasoning**:
To impute missing values in `capital_cities_by_total_population` and `navy_force_by_tonnage` columns, I will calculate the median for each column, then use the `fillna()` method to replace NaN values with their respective medians. Finally, I will display the number of missing values for these columns to confirm the imputation.

In [13]:
columns_to_impute = ['capital_cities_by_total_population', 'navy_force_by_tonnage']

for col in columns_to_impute:
    if df[col].isnull().any(): # Check if there are any missing values
        median_value = df[col].median()
        df[col] = df[col].fillna(median_value)
        print(f"Missing values in '{col}' imputed with median: {median_value}")
    else:
        print(f"No missing values found in '{col}'.")

print("\nMissing values after imputation for specified columns:")
print(df[columns_to_impute].isnull().sum())

print("\nDataFrame Info after imputation:")
df.info()

No missing values found in 'capital_cities_by_total_population'.
No missing values found in 'navy_force_by_tonnage'.

Missing values after imputation for specified columns:
capital_cities_by_total_population    0
navy_force_by_tonnage                 0
dtype: int64

DataFrame Info after imputation:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145 entries, 0 to 144
Data columns (total 61 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   country                                  145 non-null    object
 1   power_index_rank                         145 non-null    int64
 2   population                               145 non-null    int64
 3   total_personnel                          145 non-null    int64
 4   manpower_fit_for_military_service        145 non-null    int64
 5   manpower_reaching_military_age_annually  145 non-null    int64
 6   active_personnel                         145 non-null    int64
 7   reserve_personnel                        145 non-null    int64
 8   manpower_paramilitary                    145 non-null    int64
 9   capital_cities_by_total_population       145 non-null    float64
 10  total_aircraft                           145 non-null    int64
 11  fighter_aircraft                         145 non-null    int64
 12  attack_aircraft                          145 non-null    int64
 13  transport_aircraft                       145 non-null    int64
 14  aircraft_total_trainers                  145 non-null    int64
 15  aircraft_total_special_mission           145 non-null    int64
 16  aircraft_total_tanker_fleet              145 non-null    int64
 17  helicopters                              145 non-null    int64
 18  aircraft_helicopters_attack              145 non-null    int64
 19  tanks                                    145 non-null    int64
 20  armored_vehicles                         145 non-null    int64
 21  armor_self_propelled_guns_total          145 non-null    int64
 22  artillery_units                          145 non-null    int64
 23  armor_mlrs_total                         145 non-null    int64
 24  naval_assets                             145 non-null    int64
 25  navy_force_by_tonnage                    145 non-null    float64
 26  aircraft_carriers                        145 non-null    int64
 27  navy_helo_carriers                       145 non-null    int64
 28  navy_submarines                          145 non-null    int64
 29  navy_destroyers                          145 non-null    int64
 30  navy_frigates                            145 non-null    int64
 31  navy_corvettes                           145 non-null    int64
 32  navy_patrol_coastal_craft                145 non-null    int64
 33  navy_mine_warfare_craft                  145 non-null    int64
 34  defense_budget_usd                       145 non-null    int64
 35  external_debt_by_country                 145 non-null    int64
 36  gdp_usd                                  145 non-null    int64
 37  reserves_of_foreign_exchange_and_gold    145 non-null    int64
 38  major_serviceable_airports_by_country    145 non-null    int64
 39  labor_force_by_country                   145 non-null    int64
 40  major_ports_and_terminals                145 non-null    int64
 41  railway_coverage                         145 non-null    int64
 42  roadway_coverage                         145 non-null    int64
 43  oil_production_by_country                145 non-null    int64
 44  oil_consumption_by_country               145 non-null    int64
 45  proven_oil_reserves_by_country           145 non-null    int64
 46  natural_gas_production_by_country        145 non-null    int64
 47  natural_gas_consumption_by_country       145 non-null    int64
 48  proven_natural_gas_reserves_by_country   145 non-null    int64
 49  coal_production_by_country               145 non-null    int64
 50  coal_consumption_by_country              145 non-null    int64
 51  proven_coal_reserves_by_country          145 non-null    int64
 52  land_area_sq_km                          145 non-null    int64
 53  coastline_km                             145 non-null    int64
 54  border_coverage                          145 non-null    int64
 55  waterway_coverage                        145 non-null    int64
 56  capital_city                             145 non-null    object
 57  region                                   145 non-null    object
 58  continent                                145 non-null    object
 59  year                                     145 non-null    int64
 60  alliance                                 145 non-null    object
dtypes: float64(2), int64(54), object(5)
memory usage: 69.2+ KB

## Validate Cleaned Data and Save Output

### Subtask:
Validate the cleaned data by confirming there are no remaining missing values in critical columns and displaying descriptive statistics. Finally, save the cleaned DataFrame as `military_cleaned.csv` for further analysis in Tableau.

**Reasoning**:
To validate the cleaned data, I will first confirm there are no remaining missing values in the entire DataFrame. Then, I will display descriptive statistics for all numeric columns to ensure data integrity and provide a summary of the cleaned dataset. Finally, I will save the cleaned DataFrame to a CSV file named `military_cleaned.csv` as specified.

In [14]:
print("\nTotal missing values in the DataFrame after all cleaning and imputation:")
print(df.isnull().sum().sum())

print("\nDescriptive statistics for numeric columns:")
print(df.describe())

# Save the cleaned DataFrame to a CSV file
output_file_path = 'military_cleaned.csv'
df.to_csv(output_file_path, index=False)
print(f"\nCleaned data saved to {output_file_path}")

Total missing values in the DataFrame after all cleaning and imputation:
0

Descriptive statistics for numeric columns:
       power_index_rank    population  total_personnel  \
count        145.000000  1.450000e+02     1.450000e+02
mean          73.000000  5.456547e+07     2.581125e+07
std           42.001984  1.702420e+08     8.583942e+07
min            1.000000  3.640360e+05     8.372800e+04
25%           37.000000  5.650957e+06     2.392390e+06
50%           73.000000  1.469705e+07     6.351857e+06
75%          109.000000  3.879481e+07     1.794604e+07
max          145.000000  1.415043e+09     7.641234e+08

       manpower_fit_for_military_service  \
count                       1.450000e+02
mean                        2.019565e+07
std                         6.928101e+07
min                         5.023700e+04
25%                         1.912981e+06
50%                         4.096295e+06
75%                         1.403738e+07
max                         6.268642e+08

       manpower_reaching_military_age_annually  active_personnel  \
count                             1.450000e+02      1.450000e+02
mean                              8.546933e+05      1.538843e+05
std                               2.667628e+06      2.968488e+05
min                               1.820000e+03      0.000000e+00
25%                               7.199100e+04      1.840000e+04
50%                               2.048300e+05      5.000000e+04
75%                               6.250060e+05      1.620000e+05
max                               2.395518e+07      2.035000e+06

       reserve_personnel  manpower_paramilitary  \
count       1.450000e+02           1.450000e+02
mean        2.018092e+05           1.213070e+05
std         5.759480e+05           6.096424e+05
min         0.000000e+00           0.000000e+00
25%         0.000000e+00           2.000000e+03
50%         2.600000e+04           1.250000e+04
75%         1.300000e+05           5.500000e+04
max         5.000000e+06           6.800000e+06

       capital_cities_by_total_population  total_aircraft  ...  \
count                        1.450000e+02      145.000000  ...
mean                         3.237090e+06      359.579310  ...
std                          3.516291e+05     1191.106679  ...
min                          1.200000e+05        0.000000  ...
25%                          3.239000e+06       25.000000  ...
50%                          3.239000e+06       97.000000  ...
75%                          3.239000e+06      260.000000  ...
max                          6.081000e+06    13043.000000  ...

       natural_gas_consumption_by_country  \
count                        1.450000e+02
mean                         2.734661e+10
std                          9.339287e+10
min                          0.000000e+00
25%                          2.986000e+06
50%                          2.635000e+09
75%                          2.005600e+10
max                          9.143010e+11

       proven_natural_gas_reserves_by_country  coal_production_by_country  \
count                            1.450000e+02                1.450000e+02
mean                             1.377471e+12                6.399237e+07
std                              5.483828e+12                4.168309e+08
min                              0.000000e+00                0.000000e+00
25%                              0.000000e+00                0.000000e+00
50%                              8.495000e+09                1.130000e+05
75%                              2.406930e+11                4.885000e+06
max                              4.780500e+13                4.827000e+09

       coal_consumption_by_country  proven_coal_reserves_by_country  \
count                 1.450000e+02                     1.450000e+02
mean                  6.514357e+07                     7.829228e+09
std                   4.535601e+08                     3.134435e+10
min                   0.000000e+00                     0.000000e+00
25%                   2.300000e+04                     0.000000e+00
50%                   1.168000e+06                     4.000000e+07
75%                   8.637000e+06                     1.410000e+09
max                   5.313000e+09                     2.489410e+11

       land_area_sq_km   coastline_km  border_coverage  waterway_coverage  \
count     1.450000e+02     145.000000       145.000000         145.000000
mean      9.144517e+05    4695.979310      3582.972414        4345.241379
std       2.178886e+06   18166.860635      3717.386139       11728.517195
min       7.190000e+02       0.000000         0.000000           0.000000
25%       8.360000e+04      47.000000      1253.000000           0.000000
50%       2.742000e+05     713.000000      2524.000000         825.000000
75%       7.561020e+05    2640.000000      5002.000000        2800.000000
max       1.709824e+07  202080.000000     22457.000000      102000.000000

         year
count   145.0
mean   2026.0
std       0.0
min    2026.0
25%    2026.0
50%    2026.0
75%    2026.0
max    2026.0

[8 rows x 56 columns]

Cleaned data saved to military_cleaned.csv