In [2]:
import pandas as pd
import numpy as np

# **Extracting Links from the txt file**

In [1]:
links=[]
with open('all_ links_for_global_military_data.txt', 'r') as f:
    linkss = f.readlines()
    for  i in linkss:
        links.append(i.strip()[1:])

# **Extracting the html contents from the links using BeautifulSoup**

Checking the html content of first link

In [3]:
import requests
from bs4 import BeautifulSoup


response= requests.get(links[0])
soup =BeautifulSoup(response.content,'html.parser')

In [ ]:
print(soup.prettify())

<!DOCTYPE html>
<html lang="en-US">
 <head>
  <meta charset="utf-8"/>
  <title>
   Total Population by Country (2025)
  </title>
  <link href="https://www.globalfirepower.com/total-population-by-country.php" rel="canonical"/>
  <link href="https://www.globalfirepower.com/imgs/design/logo.png" rel="image_src"/>
  <style type="text/css">

In [4]:
countries=[]

In [5]:
links.remove("https://www.globalfirepower.com/capital-cities-by-total-population.php")

Data(dict) is created by  extracting the value for each country (Value and Country names are extracted using their divs from the html )and the metric name is directly derived from the link

In [6]:
import requests
from bs4 import BeautifulSoup
import time

headers = {"User-Agent": "Mozilla/5.0"}
data = {}

for url in links:

    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    metric=url.split("/")[-1].split(".")[0]
    rows = soup.select("div.picTrans.recordsetContainer")

    for row in rows:
        country = row.select_one(
            "div.countryNameContainer span.textWhite"
        )


        value = row.select_one(
            "div.valueContainer span span"
        )

        if not country or not value:
            continue

        cname = country.text.strip()
        val = value.text.strip()
        if cname not in data:
            data[cname] = {}
            countries.append(cname)

        data[cname][metric] = val.replace(",", "")

Handling the Capital Case seperately because the country name is not mentioned only in this capital_cities_population

In [7]:
i=0
response = requests.get("https://www.globalfirepower.com/capital-cities-by-total-population.php", headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

rows = soup.select("div.picTrans.recordsetContainer")
for row in  rows:
        capital = row.select_one(
            "div.countryNameContainer span.textWhite"
        )
        value = row.select_one(
            "div.valueContainer span span"
        )

        data[countries[i]]['Capital']=capital.text.strip()

        data[countries[i]]['Captal Population']=value.text.strip()
        i+=1

# **Converting it into the Dataframe and then to csv**

In [8]:


df = pd.DataFrame.from_dict(data, orient="index")
df.index.name = "Country"
df.reset_index(inplace=True)
df.to_csv("countries_data.csv", index=False)

In [9]:
 df.shape

(145, 56)

In [ ]:
df.head()

,Country,total-population-by-country,available-military-manpower,manpower-fit-for-military-service,manpower-reaching-military-age-annually,active-military-manpower,active-reserve-military-manpower,manpower-paramilitary,aircraft-total,aircraft-total-fighters,...,proven-natural-gas-reserves-by-country,coal-production-by-country,coal-consumption-by-country,proven-coal-reserves-by-country,square-land-area,coastline-coverage,border-coverage,waterway-coverage,Capital,Captal Population
0,China,1415043270,764123366,626864169,19810606,2035000,510000,625000,3309,1212,...,6654000000000 \t\t\t\t\...,4827000000 \t\t\t\t\t\t...,5313000000 \t\t\t\t\t\t...,143197000000 \t\t\t\t\t...,9596960 \t\t\t\t\t\t\r\...,14500 \t\t\t\t\t\t\r\n\...,22457 \t\t\t\t\t\t\r\n\...,27700 \t\t\t\t\t\t\r\n\...,Tokyo,"37,274,000"
1,India,1409128296,662290299,522786598,23955181,1455550,1155000,2527000,2229,513,...,1381000000000 \t\t\t\t\...,985671000 \t\t\t\t\t\t\...,1200000000 \t\t\t\t\t\t...,111052000000 \t\t\t\t\t...,3287263 \t\t\t\t\t\t\r\...,7000 \t\t\t\t\t\t\r\n\t...,13888 \t\t\t\t\t\t\r\n\...,14500 \t\t\t\t\t\t\r\n\...,New Delhi,"32,066,000"
2,United States,341963408,150463900,124816644,4445524,1328000,799500,0,13043,1790,...,13402000000000 \t\t\t\t...,548849000 \t\t\t\t\t\t\...,476044000 \t\t\t\t\t\t\...,248941000000 \t\t\t\t\t...,9833517 \t\t\t\t\t\t\r\...,19924 \t\t\t\t\t\t\r\n\...,12002 \t\t\t\t\t\t\r\n\...,41009 \t\t\t\t\t\t\r\n\...,Dhaka,"22,478,000"
3,Indonesia,281562465,137965608,114595923,4786562,400000,400000,250000,459,41,...,1408000000000 \t\t\t\t\...,659357000 \t\t\t\t\t\t\...,202283000 \t\t\t\t\t\t\...,34869000000 \t\t\t\t\t\...,1904569 \t\t\t\t\t\t\r\...,54716 \t\t\t\t\t\t\r\n\...,2958 \t\t\t\t\t\t\r\n\t...,21579 \t\t\t\t\t\t\r\n\...,Mexico City,"22,281,000"
4,Pakistan,252363571,108516336,85803614,4794908,654000,550000,500000,1399,328,...,592219000000 \t\t\t\t\t...,12712000 \t\t\t\t\t\t\r...,34027000 \t\t\t\t\t\t\r...,3064000000 \t\t\t\t\t\t...,796095 \t\t\t\t\t\t\r\n...,1046 \t\t\t\t\t\t\r\n\t...,7257 \t\t\t\t\t\t\r\n\t...,0 \t\t\t\t\t\t\r\n\t\t\...,Cairo,"21,750,000"

In [23]:
url="https://www.globalfirepower.com/powerindex.php"

In [24]:
data={}

In [26]:


url = "https://www.globalfirepower.com/countries-listing.php"
headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers, timeout=15)
soup = BeautifulSoup(response.text, "html.parser")

rows = soup.select("div.picTrans.recordsetContainer")

data = []

for row in rows:
    rank = row.select_one("div.rankNumContainer span")
    country = row.select_one("div.countryName div.longFormName")

    if not rank or not country:
        continue

    data.append({
        "country": country.text.strip(),
        "power_index_rank": int(rank.text.strip())
    })

df_rank = pd.DataFrame(data)

print(df_rank.head())

         country  power_index_rank
0  United States                 1
1         Russia                 2
2          China                 3
3          India                 4
4    South Korea                 5

In [27]:
data

[{'country': 'United States', 'power_index_rank': 1},
 {'country': 'Russia', 'power_index_rank': 2},
 {'country': 'China', 'power_index_rank': 3},
 {'country': 'India', 'power_index_rank': 4},
 {'country': 'South Korea', 'power_index_rank': 5},
 {'country': 'United Kingdom', 'power_index_rank': 6},
 {'country': 'France', 'power_index_rank': 7},
 {'country': 'Japan', 'power_index_rank': 8},
 {'country': 'Turkiye', 'power_index_rank': 9},
 {'country': 'Italy', 'power_index_rank': 10},
 {'country': 'Brazil', 'power_index_rank': 11},
 {'country': 'Pakistan', 'power_index_rank': 12},
 {'country': 'Indonesia', 'power_index_rank': 13},
 {'country': 'Germany', 'power_index_rank': 14},
 {'country': 'Israel', 'power_index_rank': 15},
 {'country': 'Iran', 'power_index_rank': 16},
 {'country': 'Spain', 'power_index_rank': 17},
 {'country': 'Australia', 'power_index_rank': 18},
 {'country': 'Egypt', 'power_index_rank': 19},
 {'country': 'Ukraine', 'power_index_rank': 20},
 {'country': 'Poland', 'power_index_rank': 21},
 {'country': 'Taiwan', 'power_index_rank': 22},
 {'country': 'Vietnam', 'power_index_rank': 23},
 {'country': 'Saudi Arabia', 'power_index_rank': 24},
 {'country': 'Thailand', 'power_index_rank': 25},
 {'country': 'Algeria', 'power_index_rank': 26},
 {'country': 'Sweden', 'power_index_rank': 27},
 {'country': 'Canada', 'power_index_rank': 28},
 {'country': 'Singapore', 'power_index_rank': 29},
 {'country': 'Greece', 'power_index_rank': 30},
 {'country': 'Nigeria', 'power_index_rank': 31},
 {'country': 'Mexico', 'power_index_rank': 32},
 {'country': 'Argentina', 'power_index_rank': 33},
 {'country': 'North Korea', 'power_index_rank': 34},
 {'country': 'Bangladesh', 'power_index_rank': 35},
 {'country': 'Netherlands', 'power_index_rank': 36},
 {'country': 'Myanmar', 'power_index_rank': 37},
 {'country': 'Norway', 'power_index_rank': 38},
 {'country': 'Portugal', 'power_index_rank': 39},
 {'country': 'South Africa', 'power_index_rank': 40},
 {'country': 'Philippines', 'power_index_rank': 41},
 {'country': 'Malaysia', 'power_index_rank': 42},
 {'country': 'Iraq', 'power_index_rank': 43},
 {'country': 'Switzerland', 'power_index_rank': 44},
 {'country': 'Denmark', 'power_index_rank': 45},
 {'country': 'Colombia', 'power_index_rank': 46},
 {'country': 'Chile', 'power_index_rank': 47},
 {'country': 'Finland', 'power_index_rank': 48},
 {'country': 'Peru', 'power_index_rank': 49},
 {'country': 'Venezuela', 'power_index_rank': 50},
 {'country': 'Romania', 'power_index_rank': 51},
 {'country': 'Ethiopia', 'power_index_rank': 52},
 {'country': 'Czechia', 'power_index_rank': 53},
 {'country': 'United Arab Emirates', 'power_index_rank': 54},
 {'country': 'Hungary', 'power_index_rank': 55},
 {'country': 'Angola', 'power_index_rank': 56},
 {'country': 'Kazakhstan', 'power_index_rank': 57},
 {'country': 'Uzbekistan', 'power_index_rank': 58},
 {'country': 'Morocco', 'power_index_rank': 59},
 {'country': 'Azerbaijan', 'power_index_rank': 60},
 {'country': 'Belgium', 'power_index_rank': 61},
 {'country': 'Bulgaria', 'power_index_rank': 62},
 {'country': 'Serbia', 'power_index_rank': 63},
 {'country': 'Syria', 'power_index_rank': 64},
 {'country': 'Ecuador', 'power_index_rank': 65},
 {'country': 'Democratic Republic of the Congo', 'power_index_rank': 66},
 {'country': 'Cuba', 'power_index_rank': 67},
 {'country': 'Austria', 'power_index_rank': 68},
 {'country': 'Sri Lanka', 'power_index_rank': 69},
 {'country': 'Belarus', 'power_index_rank': 70},
 {'country': 'Slovakia', 'power_index_rank': 71},
 {'country': 'Qatar', 'power_index_rank': 72},
 {'country': 'Sudan', 'power_index_rank': 73},
 {'country': 'Croatia', 'power_index_rank': 74},
 {'country': 'Jordan', 'power_index_rank': 75},
 {'country': 'Libya', 'power_index_rank': 76},
 {'country': 'Turkmenistan', 'power_index_rank': 77},
 {'country': 'Albania', 'power_index_rank': 78},
 {'country': 'Kuwait', 'power_index_rank': 79},
 {'country': 'Bolivia', 'power_index_rank': 80},
 {'country': 'Bahrain', 'power_index_rank': 81},
 {'country': 'Oman', 'power_index_rank': 82},
 {'country': 'Kenya', 'power_index_rank': 83},
 {'country': 'Chad', 'power_index_rank': 84},
 {'country': 'Yemen', 'power_index_rank': 85},
 {'country': 'New Zealand', 'power_index_rank': 86},
 {'country': 'Paraguay', 'power_index_rank': 87},
 {'country': 'Lithuania', 'power_index_rank': 88},
 {'country': 'Mozambique', 'power_index_rank': 89},
 {'country': 'Tunisia', 'power_index_rank': 90},
 {'country': 'Armenia', 'power_index_rank': 91},
 {'country': 'Tanzania', 'power_index_rank': 92},
 {'country': 'Cameroon', 'power_index_rank': 93},
 {'country': 'Georgia', 'power_index_rank': 94},
 {'country': 'Cambodia', 'power_index_rank': 95},
 {'country': 'Slovenia', 'power_index_rank': 96},
 {'country': 'Ireland', 'power_index_rank': 97},
 {'country': 'Mongolia', 'power_index_rank': 98},
 {'country': 'Latvia', 'power_index_rank': 99},
 {'country': 'Uruguay', 'power_index_rank': 100},
 {'country': 'Honduras', 'power_index_rank': 101},
 {'country': 'Ivory Coast', 'power_index_rank': 102},
 {'country': 'Guatemala', 'power_index_rank': 103},
 {'country': 'Mali', 'power_index_rank': 104},
 {'country': 'Kyrgyzstan', 'power_index_rank': 105},
 {'country': 'Laos', 'power_index_rank': 106},
 {'country': 'Estonia', 'power_index_rank': 107},
 {'country': 'Tajikistan', 'power_index_rank': 108},
 {'country': 'Zambia', 'power_index_rank': 109},
 {'country': 'Ghana', 'power_index_rank': 110},
 {'country': 'Zimbabwe', 'power_index_rank': 111},
 {'country': 'North Macedonia', 'power_index_rank': 112},
 {'country': 'South Sudan', 'power_index_rank': 113},
 {'country': 'Uganda', 'power_index_rank': 114},
 {'country': 'Lebanon', 'power_index_rank': 115},
 {'country': 'Namibia', 'power_index_rank': 116},
 {'country': 'Luxembourg', 'power_index_rank': 117},
 {'country': 'Afghanistan', 'power_index_rank': 118},
 {'country': 'Niger', 'power_index_rank': 119},
 {'country': 'Eritrea', 'power_index_rank': 120},
 {'country': 'Republic of the Congo', 'power_index_rank': 121},
 {'country': 'Botswana', 'power_index_rank': 122},
 {'country': 'Mauritania', 'power_index_rank': 123},
 {'country': 'Dominican Republic', 'power_index_rank': 124},
 {'country': 'Senegal', 'power_index_rank': 125},
 {'country': 'Nepal', 'power_index_rank': 126},
 {'country': 'Montenegro', 'power_index_rank': 127},
 {'country': 'El Salvador', 'power_index_rank': 128},
 {'country': 'Burkina Faso', 'power_index_rank': 129},
 {'country': 'Madagascar', 'power_index_rank': 130},
 {'country': 'Nicaragua', 'power_index_rank': 131},
 {'country': 'Bosnia and Herzegovina', 'power_index_rank': 132},
 {'country': 'Gabon', 'power_index_rank': 133},
 {'country': 'Moldova', 'power_index_rank': 134},
 {'country': 'Iceland', 'power_index_rank': 135},
 {'country': 'Panama', 'power_index_rank': 136},
 {'country': 'Beliz', 'power_index_rank': 137},
 {'country': 'Liberia', 'power_index_rank': 138},
 {'country': 'Suriname', 'power_index_rank': 139},
 {'country': 'Sierra Leone', 'power_index_rank': 140},
 {'country': 'Kosovo', 'power_index_rank': 141},
 {'country': 'Somalia', 'power_index_rank': 142},
 {'country': 'Central African Republic', 'power_index_rank': 143},
 {'country': 'Benin', 'power_index_rank': 144},
 {'country': 'Bhutan', 'power_index_rank': 145}]

In [29]:


df_rank= pd.DataFrame(data)

In [34]:
df_rank.head()
df_rank.rename(columns={'country':'Country'},inplace=True)

In [35]:
df_rank.head()

         Country  power_index_rank
0  United States                 1
1         Russia                 2
2          China                 3
3          India                 4
4    South Korea                 5

In [31]:
df.head()

,Country,total-population-by-country,available-military-manpower,manpower-fit-for-military-service,manpower-reaching-military-age-annually,active-military-manpower,active-reserve-military-manpower,manpower-paramilitary,aircraft-total,aircraft-total-fighters,...,proven-natural-gas-reserves-by-country,coal-production-by-country,coal-consumption-by-country,proven-coal-reserves-by-country,square-land-area,coastline-coverage,border-coverage,waterway-coverage,Capital,Captal Population
0,China,1415043270,764123366,626864169,19810606,2035000,510000,625000,3309,1212,...,6654000000000 \t\t\t\t\...,4827000000 \t\t\t\t\t\t...,5313000000 \t\t\t\t\t\t...,143197000000 \t\t\t\t\t...,9596960 \t\t\t\t\t\t\r\...,14500 \t\t\t\t\t\t\r\n\...,22457 \t\t\t\t\t\t\r\n\...,27700 \t\t\t\t\t\t\r\n\...,Tokyo,"37,274,000"
1,India,1409128296,662290299,522786598,23955181,1455550,1155000,2527000,2229,513,...,1381000000000 \t\t\t\t\...,985671000 \t\t\t\t\t\t\...,1200000000 \t\t\t\t\t\t...,111052000000 \t\t\t\t\t...,3287263 \t\t\t\t\t\t\r\...,7000 \t\t\t\t\t\t\r\n\t...,13888 \t\t\t\t\t\t\r\n\...,14500 \t\t\t\t\t\t\r\n\...,New Delhi,"32,066,000"
2,United States,341963408,150463900,124816644,4445524,1328000,799500,0,13043,1790,...,13402000000000 \t\t\t\t...,548849000 \t\t\t\t\t\t\...,476044000 \t\t\t\t\t\t\...,248941000000 \t\t\t\t\t...,9833517 \t\t\t\t\t\t\r\...,19924 \t\t\t\t\t\t\r\n\...,12002 \t\t\t\t\t\t\r\n\...,41009 \t\t\t\t\t\t\r\n\...,Dhaka,"22,478,000"
3,Indonesia,281562465,137965608,114595923,4786562,400000,400000,250000,459,41,...,1408000000000 \t\t\t\t\...,659357000 \t\t\t\t\t\t\...,202283000 \t\t\t\t\t\t\...,34869000000 \t\t\t\t\t\...,1904569 \t\t\t\t\t\t\r\...,54716 \t\t\t\t\t\t\r\n\...,2958 \t\t\t\t\t\t\r\n\t...,21579 \t\t\t\t\t\t\r\n\...,Mexico City,"22,281,000"
4,Pakistan,252363571,108516336,85803614,4794908,654000,550000,500000,1399,328,...,592219000000 \t\t\t\t\t...,12712000 \t\t\t\t\t\t\r...,34027000 \t\t\t\t\t\t\r...,3064000000 \t\t\t\t\t\t...,796095 \t\t\t\t\t\t\r\n...,1046 \t\t\t\t\t\t\r\n\t...,7257 \t\t\t\t\t\t\r\n\t...,0 \t\t\t\t\t\t\r\n\t\t\...,Cairo,"21,750,000"

In [38]:
df=df.merge(df_rank,on='Country')

In [39]:
df.head()

,Country,total-population-by-country,available-military-manpower,manpower-fit-for-military-service,manpower-reaching-military-age-annually,active-military-manpower,active-reserve-military-manpower,manpower-paramilitary,aircraft-total,aircraft-total-fighters,...,coal-production-by-country,coal-consumption-by-country,proven-coal-reserves-by-country,square-land-area,coastline-coverage,border-coverage,waterway-coverage,Capital,Captal Population,power_index_rank
0,China,1415043270,764123366,626864169,19810606,2035000,510000,625000,3309,1212,...,4827000000 \t\t\t\t\t\t...,5313000000 \t\t\t\t\t\t...,143197000000 \t\t\t\t\t...,9596960 \t\t\t\t\t\t\r\...,14500 \t\t\t\t\t\t\r\n\...,22457 \t\t\t\t\t\t\r\n\...,27700 \t\t\t\t\t\t\r\n\...,Tokyo,"37,274,000",3
1,India,1409128296,662290299,522786598,23955181,1455550,1155000,2527000,2229,513,...,985671000 \t\t\t\t\t\t\...,1200000000 \t\t\t\t\t\t...,111052000000 \t\t\t\t\t...,3287263 \t\t\t\t\t\t\r\...,7000 \t\t\t\t\t\t\r\n\t...,13888 \t\t\t\t\t\t\r\n\...,14500 \t\t\t\t\t\t\r\n\...,New Delhi,"32,066,000",4
2,United States,341963408,150463900,124816644,4445524,1328000,799500,0,13043,1790,...,548849000 \t\t\t\t\t\t\...,476044000 \t\t\t\t\t\t\...,248941000000 \t\t\t\t\t...,9833517 \t\t\t\t\t\t\r\...,19924 \t\t\t\t\t\t\r\n\...,12002 \t\t\t\t\t\t\r\n\...,41009 \t\t\t\t\t\t\r\n\...,Dhaka,"22,478,000",1
3,Indonesia,281562465,137965608,114595923,4786562,400000,400000,250000,459,41,...,659357000 \t\t\t\t\t\t\...,202283000 \t\t\t\t\t\t\...,34869000000 \t\t\t\t\t\...,1904569 \t\t\t\t\t\t\r\...,54716 \t\t\t\t\t\t\r\n\...,2958 \t\t\t\t\t\t\r\n\t...,21579 \t\t\t\t\t\t\r\n\...,Mexico City,"22,281,000",13
4,Pakistan,252363571,108516336,85803614,4794908,654000,550000,500000,1399,328,...,12712000 \t\t\t\t\t\t\r...,34027000 \t\t\t\t\t\t\r...,3064000000 \t\t\t\t\t\t...,796095 \t\t\t\t\t\t\r\n...,1046 \t\t\t\t\t\t\r\n\t...,7257 \t\t\t\t\t\t\r\n\t...,0 \t\t\t\t\t\t\r\n\t\t\...,Cairo,"21,750,000",12

In [40]:
df.to_csv("countries_data.csv", index=False)